#!/bin/bash

source .env
git switch $DOORWAY_BRANCH
git pull origin $DOORWAY_BRANCH
sudo docker container stop $DOORWAY_CONTAINER_NAME || true
sudo docker container rm $DOORWAY_CONTAINER_NAME || true
sudo docker build -t doorway:latest .
sudo docker run -d -p $DOORWAY_SERVER_PORT:8080 -v $PWD/config:/etc/dway/ --name dway doorway:latest
